name: CICD demo for Twitter clone
on:
  push:
    branches: main

jobs:
  Run-npm-on-Ubuntu:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "14"
    - run: npm install
