name: CICD demo for Twitter clone
on:
  push:
    branches: main

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use node js
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
      - run: npm install

    env:
      CI: true
